services:
  backend:
    restart: always
    networks:
      - default
    build:
      context: ./apps/backend
      args:
        - NODE_ENV=production
    platform: linux/amd64 # Patch for M1 Mac
    env_file:
      - ./apps/backend/.env
    ports:
      - 8000:8000

  frontend:
    restart: always
    networks:
      - default
    build:
      context: ./apps/frontend
      args:
        - NODE_ENV=production
    # platform: linux/amd64 # Patch for M1 Mac
    # env_file:
    #   - ./frontend/.env
    ports:
      - 3000:3000

    # TODO: add db service

# TODO: public directory volume for frontend, backend